GET http://localhost:8081/kafka/publish

###

GET http://localhost:8081/kafka/publish/java in 21 days
###

GET http://localhost:8081/kafka/publish/html
###

GET http://localhost:8081/kafka/publish/python
